// WARNING: Do NOT edit the input and output ports in this file in a text
// editor if you plan to continue editing the block that represents it in
// the Block Editor! File corruption is VERY likely to occur.

// Copyright (C) 2024  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions
// and other software and tools, and any partner logic
// functions, and any output files from any of the foregoing
// (including device programming or simulation files), and any
// associated documentation or information are expressly subject
// to the terms and conditions of the Intel Program License
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 23.1 (Build Build 993 05/14/2024)
// Created on Mon Aug 12 21:28:01 2024

//  Module Declaration
module mux_4ch_7seg
(
	// {{ALTERA_ARGS_BEGIN}} DO NOT REMOVE THIS LINE!
	dig1, dig2, dig3, dig4, sel, out
	// {{ALTERA_ARGS_END}} DO NOT REMOVE THIS LINE!
);
// Port Declaration

	// {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
	input [7:0] dig1;
	input [7:0] dig2;
	input [7:0] dig3;
	input [7:0] dig4;
	input [1:0] sel;
	output [7:0] out;
	// {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!
	assign out = (sel == 0) ? dig1 :
	             (sel == 1) ? dig2 :
					 (sel == 2) ? dig3 : dig4;

endmodule
